/* Any copyright is dedicated to the Public Domain.
  http://creativecommons.org/publicdomain/zero/1.0/ */

"use strict";

/*
 * THIS FILE IS AUTOGENERATED. DO NOT MODIFY BY HAND. RUN TESTS IN FIXTURES/ TO UPDATE.
 */

const { ConsoleMessage } = require("devtools/client/webconsole/new-console-output/types");

let stubPreparedMessages = new Map();
let stubPackets = new Map();


stubPreparedMessages.set("console.log('foobar', 'test')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"foobar",
		"test"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"foobar\",\"test\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(undefined)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "undefined"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"undefined\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.warn('danger, will robinson!')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "warn",
	"level": "warn",
	"messageText": null,
	"parameters": [
		"danger, will robinson!"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"warn\",\"level\":\"warn\",\"messageText\":null,\"parameters\":[\"danger, will robinson!\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(NaN)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "NaN"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"NaN\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(null)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "null"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"null\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.clear()", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "clear",
	"level": "log",
	"messageText": null,
	"parameters": [
		"Console was cleared."
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"clear\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"Console was cleared.\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('bar')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "debug",
	"messageText": "bar: 1",
	"parameters": null,
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"debug\",\"messageText\":\"bar: 1\",\"parameters\":null,\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.trace()", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "trace",
	"level": "log",
	"messageText": null,
	"parameters": [],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"trace\",\"level\":\"log\",\"messageText\":null,\"parameters\":[],\"repeatId\":null,\"stacktrace\":[{\"columnNumber\":3,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"bar\",\"language\":2,\"lineNumber\":3},{\"columnNumber\":3,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"foo\",\"language\":2,\"lineNumber\":6},{\"columnNumber\":1,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"triggerPacket\",\"language\":2,\"lineNumber\":9}],\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":3,\"column\":3}}",
	"stacktrace": [
		{
			"columnNumber": 3,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "bar",
			"language": 2,
			"lineNumber": 3
		},
		{
			"columnNumber": 3,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "foo",
			"language": 2,
			"lineNumber": 6
		},
		{
			"columnNumber": 1,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "triggerPacket",
			"language": 2,
			"lineNumber": 9
		}
	],
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 3,
		"column": 3
	}
}));

stubPreparedMessages.set("console.time('bar')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "nullMessage",
	"level": "log",
	"messageText": null,
	"parameters": null,
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"nullMessage\",\"level\":\"log\",\"messageText\":null,\"parameters\":null,\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":2,\"column\":1}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 2,
		"column": 1
	}
}));

stubPreparedMessages.set("console.timeEnd('bar')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "timeEnd",
	"level": "log",
	"messageText": "bar: 6.81ms",
	"parameters": null,
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"timeEnd\",\"level\":\"log\",\"messageText\":\"bar: 6.81ms\",\"parameters\":null,\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":3,\"column\":1}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 3,
		"column": 1
	}
}));

stubPreparedMessages.set("console.assert()", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "assert",
	"level": "error",
	"messageText": null,
	"parameters": [
		{
			"type": "object",
			"actor": "server1.conn9.child1/obj29",
			"class": "Object",
			"extensible": true,
			"frozen": false,
			"sealed": false,
			"ownPropertyLength": 3,
			"preview": {
				"kind": "Object",
				"ownProperties": {
					"message": {
						"configurable": true,
						"enumerable": true,
						"writable": true,
						"value": "a is not greater than b"
					},
					"a": {
						"configurable": true,
						"enumerable": true,
						"writable": true,
						"value": 5
					},
					"b": {
						"configurable": true,
						"enumerable": true,
						"writable": true,
						"value": 6
					}
				},
				"ownPropertiesLength": 3,
				"safeGetterValues": {}
			}
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"assert\",\"level\":\"error\",\"messageText\":null,\"parameters\":[{\"type\":\"object\",\"actor\":\"server1.conn9.child1/obj29\",\"class\":\"Object\",\"extensible\":true,\"frozen\":false,\"sealed\":false,\"ownPropertyLength\":3,\"preview\":{\"kind\":\"Object\",\"ownProperties\":{\"message\":{\"configurable\":true,\"enumerable\":true,\"writable\":true,\"value\":\"a is not greater than b\"},\"a\":{\"configurable\":true,\"enumerable\":true,\"writable\":true,\"value\":5},\"b\":{\"configurable\":true,\"enumerable\":true,\"writable\":true,\"value\":6}},\"ownPropertiesLength\":3,\"safeGetterValues\":{}}}],\"repeatId\":null,\"stacktrace\":[{\"columnNumber\":3,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"greaterThan\",\"language\":2,\"lineNumber\":3},{\"columnNumber\":1,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"triggerPacket\",\"language\":2,\"lineNumber\":6}],\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":3,\"column\":3}}",
	"stacktrace": [
		{
			"columnNumber": 3,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "greaterThan",
			"language": 2,
			"lineNumber": 3
		},
		{
			"columnNumber": 1,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "triggerPacket",
			"language": 2,
			"lineNumber": 6
		}
	],
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 3,
		"column": 3
	}
}));


stubPackets.set("console.log('foobar', 'test')", {
	"from": "server1.conn0.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"foobar",
			"test"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719504812,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(undefined)", {
	"from": "server1.conn1.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "undefined"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719505679,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.warn('danger, will robinson!')", {
	"from": "server1.conn2.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"danger, will robinson!"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "warn",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719506501,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(NaN)", {
	"from": "server1.conn3.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "NaN"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719507256,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(null)", {
	"from": "server1.conn4.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "null"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719508342,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.clear()", {
	"from": "server1.conn5.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "clear",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1472719509204,
		"timer": null,
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.count('bar')", {
	"from": "server1.conn6.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"bar"
		],
		"columnNumber": 27,
		"counter": {
			"count": 1,
			"label": "bar"
		},
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "count",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1472719510229,
		"timer": null,
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.trace()", {
	"from": "server1.conn7.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [],
		"columnNumber": 3,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "bar",
		"groupName": "",
		"level": "trace",
		"lineNumber": 3,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1472719511376,
		"timer": null,
		"stacktrace": [
			{
				"columnNumber": 3,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "bar",
				"language": 2,
				"lineNumber": 3
			},
			{
				"columnNumber": 3,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "foo",
				"language": 2,
				"lineNumber": 6
			},
			{
				"columnNumber": 1,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "triggerPacket",
				"language": 2,
				"lineNumber": 9
			}
		],
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.time('bar')", {
	"from": "server1.conn8.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"bar"
		],
		"columnNumber": 1,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "time",
		"lineNumber": 2,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1472719512532,
		"timer": {
			"name": "bar",
			"started": 910.1750000000001
		},
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.timeEnd('bar')", {
	"from": "server1.conn8.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"bar"
		],
		"columnNumber": 1,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "timeEnd",
		"lineNumber": 3,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1472719512539,
		"timer": {
			"duration": 6.814999999999941,
			"name": "bar"
		},
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.assert()", {
	"from": "server1.conn9.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "object",
				"actor": "server1.conn9.child1/obj29",
				"class": "Object",
				"extensible": true,
				"frozen": false,
				"sealed": false,
				"ownPropertyLength": 3,
				"preview": {
					"kind": "Object",
					"ownProperties": {
						"message": {
							"configurable": true,
							"enumerable": true,
							"writable": true,
							"value": "a is not greater than b"
						},
						"a": {
							"configurable": true,
							"enumerable": true,
							"writable": true,
							"value": 5
						},
						"b": {
							"configurable": true,
							"enumerable": true,
							"writable": true,
							"value": 6
						}
					},
					"ownPropertiesLength": 3,
					"safeGetterValues": {}
				}
			}
		],
		"columnNumber": 3,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "greaterThan",
		"groupName": "",
		"level": "assert",
		"lineNumber": 3,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1472719513466,
		"timer": null,
		"stacktrace": [
			{
				"columnNumber": 3,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "greaterThan",
				"language": 2,
				"lineNumber": 3
			},
			{
				"columnNumber": 1,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "triggerPacket",
				"language": 2,
				"lineNumber": 6
			}
		],
		"workerType": "none",
		"category": "webdev"
	}
});


module.exports = {
  stubPreparedMessages,
  stubPackets,
}