/* Any copyright is dedicated to the Public Domain.
  http://creativecommons.org/publicdomain/zero/1.0/ */

"use strict";

/*
 * THIS FILE IS AUTOGENERATED. DO NOT MODIFY BY HAND. RUN TESTS IN FIXTURES/ TO UPDATE.
 */

const { ConsoleMessage } = require("devtools/client/webconsole/new-console-output/types");

let stubPreparedMessages = new Map();
let stubPackets = new Map();


stubPreparedMessages.set("console.log('foobar', 'test')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"foobar",
		"test"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"foobar\",\"test\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(undefined)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "undefined"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"undefined\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.warn('danger, will robinson!')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "warn",
	"level": "warn",
	"messageText": null,
	"parameters": [
		"danger, will robinson!"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"warn\",\"level\":\"warn\",\"messageText\":null,\"parameters\":[\"danger, will robinson!\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(NaN)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "NaN"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"NaN\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log(null)", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		{
			"type": "null"
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[{\"type\":\"null\"}],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log('鼬')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"鼬"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"鼬\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.clear()", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "clear",
	"level": "log",
	"messageText": null,
	"parameters": [
		"Console was cleared."
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"clear\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"Console was cleared.\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('bar')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "debug",
	"messageText": "bar: 1",
	"parameters": null,
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"debug\",\"messageText\":\"bar: 1\",\"parameters\":null,\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.assert(false, {message: 'foobar'})", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "assert",
	"level": "error",
	"messageText": null,
	"parameters": [
		{
			"type": "object",
			"actor": "server1.conn8.child1/obj29",
			"class": "Object",
			"extensible": true,
			"frozen": false,
			"sealed": false,
			"ownPropertyLength": 1,
			"preview": {
				"kind": "Object",
				"ownProperties": {
					"message": {
						"configurable": true,
						"enumerable": true,
						"writable": true,
						"value": "foobar"
					}
				},
				"ownPropertiesLength": 1,
				"safeGetterValues": {}
			}
		}
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"assert\",\"level\":\"error\",\"messageText\":null,\"parameters\":[{\"type\":\"object\",\"actor\":\"server1.conn8.child1/obj29\",\"class\":\"Object\",\"extensible\":true,\"frozen\":false,\"sealed\":false,\"ownPropertyLength\":1,\"preview\":{\"kind\":\"Object\",\"ownProperties\":{\"message\":{\"configurable\":true,\"enumerable\":true,\"writable\":true,\"value\":\"foobar\"}},\"ownPropertiesLength\":1,\"safeGetterValues\":{}}}],\"repeatId\":null,\"stacktrace\":[{\"columnNumber\":27,\"filename\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"functionName\":\"triggerPacket\",\"language\":2,\"lineNumber\":1}],\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": [
		{
			"columnNumber": 27,
			"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
			"functionName": "triggerPacket",
			"language": 2,
			"lineNumber": 1
		}
	],
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log('hello \nfrom \rthe \"string world!')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"hello \nfrom \rthe \"string world!"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"hello \\nfrom \\rthe \\\"string world!\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.log('úṇĩçödê țĕșť')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"úṇĩçödê țĕșť"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"úṇĩçödê țĕșť\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('a')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"úṇĩçödê țĕșť"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"úṇĩçödê țĕșť\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('b')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"úṇĩçödê țĕșť"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"úṇĩçödê țĕșť\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('barasdf')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"úṇĩçödê țĕșť"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"úṇĩçödê țĕșť\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));

stubPreparedMessages.set("console.count('barista')", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": null,
	"parameters": [
		"úṇĩçödê țĕșť"
	],
	"repeat": 1,
	"repeatId": "{\"id\":null,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":null,\"parameters\":[\"úṇĩçödê țĕșť\"],\"repeatId\":null,\"stacktrace\":null,\"frame\":{\"source\":\"http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js\",\"line\":1,\"column\":27}}",
	"stacktrace": null,
	"frame": {
		"source": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"line": 1,
		"column": 27
	}
}));


stubPackets.set("console.log('foobar', 'test')", {
	"from": "server1.conn0.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"foobar",
			"test"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868908866,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(undefined)", {
	"from": "server1.conn1.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "undefined"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868909853,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.warn('danger, will robinson!')", {
	"from": "server1.conn2.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"danger, will robinson!"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "warn",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868910767,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(NaN)", {
	"from": "server1.conn3.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "NaN"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868911765,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log(null)", {
	"from": "server1.conn4.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "null"
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868912674,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log('鼬')", {
	"from": "server1.conn5.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"鼬"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868913729,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.clear()", {
	"from": "server1.conn6.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "clear",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1473868914797,
		"timer": null,
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.count('bar')", {
	"from": "server1.conn7.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"bar"
		],
		"columnNumber": 27,
		"counter": {
			"count": 1,
			"label": "bar"
		},
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "count",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"timeStamp": 1473868915775,
		"timer": null,
		"workerType": "none",
		"styles": [],
		"category": "webdev"
	}
});

stubPackets.set("console.assert(false, {message: 'foobar'})", {
	"from": "server1.conn8.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			{
				"type": "object",
				"actor": "server1.conn8.child1/obj29",
				"class": "Object",
				"extensible": true,
				"frozen": false,
				"sealed": false,
				"ownPropertyLength": 1,
				"preview": {
					"kind": "Object",
					"ownProperties": {
						"message": {
							"configurable": true,
							"enumerable": true,
							"writable": true,
							"value": "foobar"
						}
					},
					"ownPropertiesLength": 1,
					"safeGetterValues": {}
				}
			}
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "assert",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868916842,
		"timer": null,
		"stacktrace": [
			{
				"columnNumber": 27,
				"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
				"functionName": "triggerPacket",
				"language": 2,
				"lineNumber": 1
			}
		],
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log('hello \nfrom \rthe \"string world!')", {
	"from": "server1.conn9.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"hello \nfrom \rthe \"string world!"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868917842,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.log('úṇĩçödê țĕșť')", {
	"from": "server1.conn10.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"úṇĩçödê țĕșť"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868918875,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.count('a')", {
	"from": "server1.conn11.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"úṇĩçödê țĕșť"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868919992,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.count('b')", {
	"from": "server1.conn12.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"úṇĩçödê țĕșť"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868921066,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.count('barasdf')", {
	"from": "server1.conn13.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"úṇĩçödê țĕșť"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868922219,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});

stubPackets.set("console.count('barista')", {
	"from": "server1.conn14.child1/consoleActor2",
	"type": "consoleAPICall",
	"message": {
		"arguments": [
			"úṇĩçödê țĕșť"
		],
		"columnNumber": 27,
		"counter": null,
		"filename": "http://example.com/browser/devtools/client/webconsole/new-console-output/test/fixtures/stub-generators/test-tempfile.js",
		"functionName": "triggerPacket",
		"groupName": "",
		"level": "log",
		"lineNumber": 1,
		"originAttributes": {
			"addonId": "",
			"appId": 0,
			"inIsolatedMozBrowser": false,
			"privateBrowsingId": 0,
			"signedPkg": "",
			"userContextId": 0
		},
		"private": false,
		"styles": [],
		"timeStamp": 1473868923393,
		"timer": null,
		"workerType": "none",
		"category": "webdev"
	}
});


module.exports = {
  stubPreparedMessages,
  stubPackets,
}