/* Any copyright is dedicated to the Public Domain.
  http://creativecommons.org/publicdomain/zero/1.0/ */

"use strict";

/*
 * THIS FILE IS AUTOGENERATED. DO NOT MODIFY BY HAND. RUN TESTS IN FIXTURES/ TO UPDATE.
 */

const { ConsoleMessage } = require("devtools/client/webconsole/new-console-output/types");

let stubPreparedMessages = new Map();
let stubPackets = new Map();


stubPreparedMessages.set("tabNavigated", new ConsoleMessage({
	"id": "1",
	"allowRepeating": true,
	"source": "console-api",
	"type": "log",
	"level": "log",
	"messageText": "Navigated to http://example.com/",
	"parameters": null,
	"repeat": 1,
	"repeatId": "{\"id\":1,\"allowRepeating\":true,\"source\":\"console-api\",\"type\":\"log\",\"level\":\"log\",\"messageText\":\"Navigated to http://example.com/\",\"parameters\":null,\"repeatId\":\"{\\\"id\\\":null,\\\"allowRepeating\\\":true,\\\"source\\\":\\\"console-api\\\",\\\"type\\\":\\\"log\\\",\\\"level\\\":\\\"log\\\",\\\"messageText\\\":\\\"Navigated to http://example.com/\\\",\\\"parameters\\\":null,\\\"repeatId\\\":null,\\\"stacktrace\\\":null,\\\"frame\\\":null}\",\"stacktrace\":null,\"frame\":null}",
	"stacktrace": null,
	"frame": null
}));


stubPackets.set("tabNavigated", {
	"from": "server1.conn0.child1/tab1",
	"type": "tabNavigated",
	"url": "http://example.com/",
	"nativeConsoleAPI": true,
	"state": "start",
	"isFrameSwitching": false
});


module.exports = {
  stubPreparedMessages,
  stubPackets,
}